<?php
require_once '1st.php';
$num = 123;
echo $num . PHP_EOL;
$a = 10;
$a = 20;
echo $a . PHP_EOL;
$a = 1 + 2 + 3;
echo $a . PHP_EOL;
fatamorgana('Математические операции с переменными в PHP');
$a = 10;
$b = 2;
$c = 10;
$d = 5;
$res = $c + $d;
echo $a + $b . PHP_EOL; echo $a - $b . PHP_EOL; echo $a * $b . PHP_EOL; echo $a / $b . PHP_EOL; echo $res . PHP_EOL;
$a = 1;
$b = 2;
$c = 3;
echo $a + $b + $c . PHP_EOL;
$a = 10;
$b = 5;
$c = $a - $b;
$d = 7;
$res = $c + $d;
echo $res . PHP_EOL;
fatamorgana('Дроби в PHP');
$a = 1.5;
$b = 0.75;
echo $a + $b . PHP_EOL;
fatamorgana('Отрицательные числа в PHP');
$a = -100; echo $a . PHP_EOL;
$a = -32; echo -$a . PHP_EOL;
fatamorgana('Остаток от деления в PHP');
$a = 10; $b = 3; echo $a % $b . PHP_EOL;
fatamorgana('Возведение в степень в PHP');
$a = 2; $b = 10; echo $a ** $b . PHP_EOL;
fatamorgana('Сложение строк в PHP');
$str = 'hello'; echo $str . PHP_EOL;
$str = 'abc'; $str2 = 'def'; echo $str . $str2 . PHP_EOL;
fatamorgana('Пробелы при сложении строк в PHP');
$str = 'hello'; $str2 = ' world'; echo $str . $str2 . PHP_EOL;
fatamorgana('Длина строки в PHP');
$str = 'hauntingclaire'; echo strlen($str) . PHP_EOL;
fatamorgana('Проблема с кириллицей в PHP');
echo strlen('привет') . PHP_EOL; echo mb_strlen('привет') . PHP_EOL;
fatamorgana('Работа с HTML тегами в PHP'); // разнообразие в применении
echo '<i>hello</i>' . PHP_EOL; echo '<br>123456789</br>' . PHP_EOL;
fatamorgana('Атрибуты тегов в PHP');
echo '<a href="1st.php">ссылка</a>';
fatamorgana('Логические значения в PHP');
$a = true; $b = false; echo $a . PHP_EOL; echo $b . PHP_EOL;
fatamorgana('Значение null в PHP');
$a = null; echo $a . PHP_EOL; // echo $doesntexist . PHP_EOL; // PHP Warning:  Undefined variable $doesntexist
fatamorgana('Принудительное преобразование в целые числа на PHP');
$test = '12345'; echo (int)$test . PHP_EOL; var_dump($test); var_dump((int)$test);
fatamorgana('Принудительное преобразование в дробные числа в PHP');
$test = '12.345'; echo (float)$test . PHP_EOL; var_dump($test); var_dump((float)$test);
fatamorgana('Преобразование дроби к целому числу в PHP');
$test = 12.345; echo (int)$test . PHP_EOL; var_dump($test); var_dump((int)$test);
fatamorgana('Преобразование к строке в PHP');
$test = 12.345; echo (string)$test . PHP_EOL; var_dump($test); var_dump((string)$test);
$test = 12345; echo (string)$test . PHP_EOL; var_dump($test); var_dump((string)$test);
fatamorgana('Получение символов строки на PHP');
$str = 'abcde'; echo $str[0]; echo $str[2]; echo $str[4] . PHP_EOL;
$str = 'abcde'; echo $str[4]; echo $str[3]; echo $str[2]; echo $str[1]; echo $str[0] . PHP_EOL;
$str = 'abcde'; $num = $str[0]; echo $num . PHP_EOL;
fatamorgana('Последний символ строки PHP');
$str = 'abcde'; $last = strlen($str) - 1; echo $str[$last]. PHP_EOL; $prelast = strlen($str) - 2; echo $str[$prelast]. PHP_EOL;
fatamorgana('Цифры в строке на PHP');
$str = '12345'; echo $str[0] + $str[1] + $str[2] + $str[3] + $str[4] . PHP_EOL;
fatamorgana('Обращение к цифрам числа на PHP');
$num = 12345; $str = (string)$num; echo $str[0] + $str[1] + $str[2] + $str[3] + $str[4] . PHP_EOL;
fatamorgana('Сокращенные операции в PHP');
$num = 47; $num += 7; $num -= 18; $num *= 10; $num /= 15; $str = 'a'; $str .= 'b'; $str .= 'c'; echo $num . $str . PHP_EOL;
fatamorgana('Операции инкремента и декремента в PHP');
$num = 10; $num++; $num++; $num--; echo $num . PHP_EOL;
fatamorgana('Практика на операции в PHP');
$seconds = 86400 * 365; echo $seconds . PHP_EOL; // сколько секунд в году
$minutes = 60 * 24 * 365; echo $minutes . PHP_EOL; // сколько минут в году
fatamorgana('Массивы в PHP');
$array = [1, 2, 3]; var_dump($array);
fatamorgana('Как вывести отдельный элемент массива в PHP');
echo $array[0] . PHP_EOL; echo $array[1] . PHP_EOL; echo $array[2] . PHP_EOL;
$array = ['a', 'b', 'c', 'd']; echo $array[0] . '+' . $array[1] . '+' . $array[2] . '+' . $array[3] . PHP_EOL;
$array = [1, 2, 3]; echo $array[0] + $array[1] + $array[2] . PHP_EOL;
$array = [2, 5, 3, 9]; $res = $array[0] * $array[1] + $array[2] * $array[3]; echo $res . PHP_EOL;
fatamorgana('Ассоциативные массивы в PHP');
$array = [1 => 'a', 2 => 'b', 3 => 'c']; echo $array[1]; echo $array[2]; echo $array[3] . PHP_EOL;
fatamorgana('Хитрость с ключами в PHP');
$array = [1 => 'Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']; echo $array[1] . PHP_EOL;
fatamorgana('Строковые ключи в PHP');
$user = ['name' => 'Alex', 'lastname' => 'Smith', 'patronymic' => 'Petrov']; echo $user['name'] . ' '; echo $user['lastname'] . ' '; echo $user['patronymic'] . PHP_EOL;
$date = ['day' => '30' , 'month' => '08' , 'year' => '2024']; echo $date['year'] . '-' . $date['month'] . '-' . $date['day'] . PHP_EOL;
fatamorgana('Длина массива в PHP');
echo count($array) . PHP_EOL; // янверь февраль март апрель май и т.д. 12 месяцев
$array = ['a' => 1, 'b' => 2, 'c' => 3, 'd' => 4]; echo count($array) . PHP_EOL;
fatamorgana('Последний элемент массива в PHP');
$array = ['a', 'b', 'c', 'd', 'e'];; echo end($array) . PHP_EOL;
echo (count($array) - 1) . ' '; echo (count($array) - 2) . PHP_EOL; // последний и предпоследний массив
fatamorgana('Изменение элементов массива в PHP');
$array = ['a' => 1, 'b' => 2, 'c' => 3]; $array['a'] = 'f'; $array['b'] = 'r'; $array['c'] = 'i'; $array[3] = 'd'; echo $array[0] . PHP_EOL;
fatamorgana('Перезапись элементов массива в PHP');
$array = ['a' => 1, 'b' => 2, 'c' => 3]; $array['a'] += 3; $array['b'] += 3; $array['c'] += 3; echo $array['a'] . ' ' . $array['b'] . ' ' . $array['c'] . PHP_EOL;